### ISSUE TITLE
need help with simple example

### ISSUE THREAD

**Issue by ryanlowdermilk** [Code52/jibbr#39]
Wondering why this doesn't work. 

Any ideas?

http://gist.github.com/1604975

**Comment by pietervp** [comment]
What's the exact problem? Checf if your project lives under the Extensions folder of Jibbr, the console app only copies Sprockets from there.

**Comment by ryanlowdermilk** [comment]
pietervp - thx for responding. yes, i have the C# class project under the Extensions. to answer your question, i'm not exactly sure what the problem is. i can see channel commands in the "output" window under Visual Studio, but the bot doesn't respond.

**Comment by cyberzed** [comment]
What are you exactly writing when you want to activate it...

It should be exactly "weather 93063", which I assume you do :) one thing I've had happen to me during the first pieces was a missing recompilation before it actually worked due to assemblies only being copied at the points where the consolebot is compiled.

Have you checked if the sprocket is loaded into the list of "handlers"?

**Comment by ryanlowdermilk** [comment]
cyberzed, thx for the reply. yes, you're correct, i'm typing "weather 93063"

i searched around and found a "handlers" section but i didn't notice other sprockets listed e.g. IPityTheFoolSprocket, SampleAnnouncement or SampleSprocket?

How do I check the list of handlers?

Also, what happens if you try to implement the gist code above?
http://gist.github.com/1604975

Thanks, cyberzed

**Comment by ryanlowdermilk** [comment]
Ok, @cyberzed helped my find out the issue. 

In Visual Studio, I right clicked on the "Extensions" folder and created my project. However, this resulted in the project being created in the [root] folder instead of the "Extensions" folder, which is located one directory up from the root.

Moved my project the the "Extensions" folder in Explorer, re-added it to my Solution and BOOM!

Thanks again, @cyberzed
