### ISSUE TITLE
Problem loading project

### ISSUE THREAD

**Issue by jeffersonhwang** [Code52/jibbr#40]
Hi,

At the moment, I am experience a problem when loading the project.  

The project is unable to load Jabbot.AspNetBotHost when I open the project in VS2010 because apparently I'm missing IIS 6 and Asp.net  I have already downloaded the Microsoft .Net Service Pack and IIS 7 Express.  What steps can I take to resolve this issue?

Thanks!

**Comment by ghost** [comment]
What was the exact error given?

**Comment by jeffersonhwang** [comment]
The exact error is as below:

C:\Users\Jefferson Hwang.ssh\jibbr\Jabbot.AspNetBotHost\Jabbot.AspNetBotHost.csproj : error  : The Web Application Project Jabbot.AspNetBotHost is configured to use IIS. IIS is not installed on this computer. To access local IIS Web sites, you must install the following IIS components:

```
  Internet Information Services
  IIS 6 Metabase and IIS 6 Configuration Compatibility
  ASP.NET
```

In addition, you must run Visual Studio in the context of an administrator account.

For more information, press F1.

**Comment by ghost** [comment]
If you use Microsoft's ["Web Platform Installer"](http://www.microsoft.com/web/downloads/platform.aspx), then get it to turn on the "recommended web config", that should solve those problems.

**Comment by jeffersonhwang** [comment]
Thanks! I'll give it a try.

**Comment by jeffersonhwang** [comment]
So I got the project to load, but I'm experiencing an issue with building/executing the project.  When I attempt to build Jabbot.ConsoleBotHost it gives me the error:

Jabbot.ConsoleBotHost -> C:\Users\Jefferson Hwang.ssh\jibbr\Jabbot.ConsoleBotHost\bin\Release\Jabbot.ConsoleBotHost.exe
  'C:\Users\Jefferson' is not recognized as an internal or external command

I'm assuming because of the space in between "Jefferson" and "Hwang", it assumes the command has ended.
Did anyone else get this issue? What steps can be taken to resolve it?

**Comment by ghost** [comment]
Move the code folder to something like C:\code\jibbr. Not ideal, but its a quick fix so you can get to using it.
