### ISSUE TITLE
Status Sprocket?

### ISSUE THREAD

**Issue by jeffersonhwang** [Code52/jibbr#55]
Every user can set his/her status to something they're working on or whatever they're listening to, etc.  

I can't get onto the chat room jabbr at the moment for some reason, but I assume there is a command "whois" or something similar.

Ex)

Someone's who is interested in what Aeoth's currently working on can type whois Aeoth and see his status?

-- If anyone has a suggestion to improve this before I go ahead and work on it, feel free to contribute.

**Comment by andrewtobin** [comment]
/who

What do you want to do with the sprocket?

I've added some methods to GetUserInfo so that you can see the status in there if you want, you can also send a command to set Status, I think it's bot.ChangeNote(note)

**Comment by jeffersonhwang** [comment]
It's the idea of the Facebook status message, where users can see what their peers are up to.

As for the note you mentioned, is the note visible to all users or only the user who set the note. My idea was more inclined towards everyone versus just yourself.  So for example:

Ex)

> Status Aeoth
> 
> Bot: Aeoth is currently drawing the Jibbr logo.

**Comment by andrewtobin** [comment]
In Jabbr, do you see the paper clip next to peoples names? hover over it - that's a note/status note

**Comment by jeffersonhwang** [comment]
while we're on the topic Jabbr...I can't seem to see anyone or talk, although I was just in there yesterday.  I clicked on the jabbr link from the code52.org website, and I'm just met with an empty Lobby.

**Comment by andrewtobin** [comment]
Jabbr can be a bitch, unfortunately - try refreshing... sometimes it's just
not good - it's hosting needs to be better but it's on a free Apphb plan.

On Sun, Jan 15, 2012 at 6:03 PM, archgold <
reply@reply.github.com
